version: '3.9'
services:
    backend:
      build: .
      ports:
        - 5000:5000
      volumes:
        - .:/app
      depends_on: 
        - db
    db:
      image: mysql:5.7.22
      command: --port=8889
      restart: always
      environment:
        MYSQL_DATABASE: admin
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        
      volumes:
        - .dbdata:/var/lib/mysql
      ports:
        - 8889:8889